### ISSUE TITLE
Tld extraction issue

### ISSUE THREAD

**Issue by StefSleepy** [stricaud/faup#113]
faup -f tld firehose.eu-west-1.amazonaws.com
result should be ".com" but instead I get "eu-west-1.amazonaws.com"
Is this an issue with the list?

**Comment by stricaud** [comment]
There is none, this is actually the expected behavior as this is a special case. If you want to not follow the mozilla suffix list of tld extraction, you can use the -t flag, such as:

`$ faup -t -f tld firehose.eu-west-1.amazonaws.com
com
`
The public suffix list is available from this page https://publicsuffix.org/
