### ISSUE TITLE
Faup wrong results

### ISSUE THREAD

**Issue by c-x** [stricaud/faup#67]
Pulled and compiled the current version, seems to have issues (invalid domain, invalid tld)

```
# echo “http://www.nonexistent.co.uk” | faup -o json
{
	"scheme": "“http",
	"credential": "",
	"subdomain": "www.nonexistent",
	"domain": "co.uk”",
	"domain_without_tld": "co",
	"host": "www.nonexistent.co.uk”",
	"tld": "uk”",
	"port": "",
	"resource_path": "",
	"query_string": "",
	"fragment": "",
	"url_type": "unknown_tld"
}
```

**Comment by stricaud** [comment]
When I copy/paste your line, the double quotes character is not taken as quotes since they are not the char ". So it makes sense this is the case since it takes this strange character as something part of the TLD. I don't want to change this behavior as I want to handle weird characters TLDs may have.

Anyway, tested in the current git and it seems all fine. I can close.

$ echo "http://www.nonexistent.co.uk" | ./src/tools/faup -o json
{
	"scheme": "http",
	"credential": "",
	"subdomain": "www",
	"domain": "nonexistent.co.uk",
	"domain_without_tld": "nonexistent",
	"host": "www.nonexistent.co.uk",
	"tld": "co.uk",
	"port": "",
	"resource_path": "",
	"query_string": "",
	"fragment": "",
	"url_type": "mozilla_tld"
}
