### ISSUE TITLE
No module named 'pyfaup'

### ISSUE THREAD

**Issue by arnydo** [stricaud/faup#85]
Faup has been built/installed and running great.
However, when trying to run via Python I get the following:

>>> from pyfaup.faup import Faup
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'pyfaup'

Any advice?

**Comment by fedelemantuano** [comment]
Did you setup Python module with setup.py

**Comment by robertnixon2003** [comment]
I am having a similar issue.

from pyfaup.faup import Faup   File "<frozen importlib._bootstrap>", line 969, in _find_and_load   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible   File "/usr/local/lib/python3.5/dist-packages/pyfaup-1.0-py3.5.egg/pyfaup/__init__.py", line 20, in <module>   File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary     return self._dlltype(name)   File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__     self._handle = _dlopen(self._name, mode) OSError: libfaupl.so.1: cannot open shared object file: No such file or directory )

**Comment by robertnixon2003** [comment]
>>> import pyfaup
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/usr/local/lib/python3.5/dist-packages/pyfaup-1.0-py3.5.egg/pyfaup/__init__.py", line 20, in <module>
  File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libfaupl.so.1: cannot open shared object file: No such file or directory
>>>

**Comment by arnydo** [comment]
"Facepalm"

I ran setup.py and it worked great :-)

It was hidden down in the folder structure so I didn't see it at first.

Thanks!

**Comment by fedelemantuano** [comment]
@robertnixon2003 is [this errror](https://github.com/stricaud/faup#why-do-i-receive-the-error-libfauplso1-cannot-open-shared-object-file-when-trying-to-run-faup)?

**Comment by arnydo** [comment]
Installed via /src/lib/bindings/python/setup.py

**Comment by fedelemantuano** [comment]
If you have last version of `pip`, you can use:

```
pip install -e "git+https://github.com/stricaud/faup.git#egg=pyfaup&subdirectory=src/lib/bindings/python"
```

**Comment by packetwatch** [comment]
Hi all,

This feels like an instance of this issue, but the fix is not working. I installed through pip and also through the 'python setup.py install' route in /src/lib/bindings/python. Ubuntu 18 with MISP up to date. I'm trying to get mail_to_misp to run and failing on the test, 'mail_to_misp.py -h'. Results below:

server-name:/opt/mail_to_misp/faup/src/lib/bindings/python# python setup.py install
running install
running bdist_egg
running egg_info
writing pyfaup.egg-info/PKG-INFO
writing top-level names to pyfaup.egg-info/top_level.txt
writing dependency_links to pyfaup.egg-info/dependency_links.txt
reading manifest file 'pyfaup.egg-info/SOURCES.txt'
writing manifest file 'pyfaup.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/pyfaup
copying build/lib.linux-x86_64-2.7/pyfaup/bind.py -> build/bdist.linux-x86_64/egg/pyfaup
copying build/lib.linux-x86_64-2.7/pyfaup/__init__.py -> build/bdist.linux-x86_64/egg/pyfaup
copying build/lib.linux-x86_64-2.7/pyfaup/faup.py -> build/bdist.linux-x86_64/egg/pyfaup
copying build/lib.linux-x86_64-2.7/pyfaup/functions.py -> build/bdist.linux-x86_64/egg/pyfaup
byte-compiling build/bdist.linux-x86_64/egg/pyfaup/bind.py to bind.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyfaup/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyfaup/faup.py to faup.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyfaup/functions.py to functions.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying pyfaup.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyfaup.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyfaup.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying pyfaup.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/pyfaup-1.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing pyfaup-1.0-py2.7.egg
Copying pyfaup-1.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Removing pyfaup 1.0 from easy-install.pth file
Adding pyfaup 1.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/pyfaup-1.0-py2.7.egg
Processing dependencies for pyfaup==1.0
Finished processing dependencies for pyfaup==1.0


Then:

server-name:/opt/mail_to_misp# ./mail_to_misp.py -h
Traceback (most recent call last):
  File "./mail_to_misp.py", line 12, in <module>
    from mail2misp import Mail2MISP
  File "/opt/mail_to_misp/mail2misp/__init__.py", line 3, in <module>
    from .mail2misp import Mail2MISP
  File "/opt/mail_to_misp/mail2misp/mail2misp.py", line 13, in <module>
    from pyfaup.faup import Faup
ModuleNotFoundError: No module named 'pyfaup'


It seems like the install succeeds but the module is not in a path maybe?

Any help is appreciated!
